steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/5bss/epic", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/5bss/epic"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "epic",
        "--image",
        "gcr.io/5bss/epic",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
